### ISSUE TITLE
Latest Truffle supports function overloading

### ISSUE THREAD

**Issue by gakonst** [celer-network/cChannel-eth#5]
> The current version of truffle doesn’t support function overloading. This release uses different names for deposit functions for now and waits for support of future truffle version.

Latest truffle supports function overloading https://github.com/trufflesuite/truffle/releases/tag/v5.0.0-beta.0#overloaded-solidity-methods, raising this FYI in-case you want to adapt your code

**Comment by Dominator008** [comment]
Thanks! The upcoming open-source release will be based on solidity 0.5.0 / truffle 5.0.0 and will make use of overloading if necessary.
